<?php

require_once './Page.php';

class Booking extends Page
{
    protected function __construct()
    {
        parent::__construct();
    }

    protected function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    protected function getViewData(){}

    protected function generateView()
    {
        $this->generatePageHeader('Booking'); // TODO: Change the autogenerated stub

        echo <<<EOT
     <form method="post" action="Booking.php" onsubmit="">
      <div>
      <nav>
<a href="Date.php">FlightDate</a> |
<a href="Customer.php">Customer</a> |
<a href="">Target</a> |
<a href="">Target</a>
</nav>
</div>  
</form>   
EOT;


    }

    public static function main()
    {
        try {
            $page = new Booking();
            $page->generateView();

        } catch (Exception $exception) {
            header("Content-type: text/plain");
            echo $exception->getMessage();
        }
    }


}

Booking::main();