<?php

require_once './Page.php';

class Date extends Page
{

    protected function __construct()
    {
        parent::__construct();
    }

    protected function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }


    protected function generateView(){
        $this->generatePageHeader('Date');

        echo <<<EOT
        
    
EOT;
    $this->generatePageFooter();
    }


public static function main(){
    try{

        $page = new Date();
        $page->generateView();
    }
    catch(Exception $exception){
        header("Content-type:text/plain");
        $exception->getMessage();
    }
}

}Date::main();